name: 'Test wlc'
description: 'Test wlc'

runs:
  using: "composite"
  steps:
      - name: Install wlc
        run: pip3 install wlc
        shell: bash
        
      - name: Lock weblate repos
        run: ${{ github.action_path }}/lockWeblate.sh
        shell: bash
